#!/usr/bin/env python3
"""
Generate requirements.txt files from pyproject.toml.

Dependencies are declared ONLY in pyproject.toml. This script extracts them
and writes the requirements-*.txt files to keep legacy tooling compatible.

Usage:
    python tools/generate_requirements.py          # regenerate all files
    python tools/generate_requirements.py --check  # verify files are up-to-date
"""
from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path

try:
    import tomllib
except ImportError:
    try:
        import tomli as tomllib
    except ImportError:
        print(
            "ERROR: tomllib is not available. Install tomli for Python < 3.11, "
            "or use Python 3.11+.",
            file=sys.stderr,
        )
        sys.exit(1)


ROOT = Path(__file__).resolve().parent.parent
PYPROJECT = ROOT / "pyproject.toml"
PKG_NAME = "sweetviz"

HEADER = """\
# AUTOGENERATED from pyproject.toml — DO NOT EDIT BY HAND
#
# Sweetviz declares ALL dependencies in pyproject.toml.
# This file exists only for compatibility with tools that require
# requirements.txt style input.
#
# To regenerate:  python tools/generate_requirements.py
# To install:     pip install -e ".[dev]"   (or test / docs / notebook / comet / all)
#
"""

_SELF_REF = re.compile(rf"^{re.escape(PKG_NAME)}\[([^\]]+)\]$")


def parse_pyproject() -> dict:
    with open(PYPROJECT, "rb") as f:
        return tomllib.load(f)


def flatten_dep(dep: str) -> str:
    return dep.strip()


def expand_deps(deps: list[str], all_opts: dict[str, list[str]], seen: set[str] | None = None) -> list[str]:
    if seen is None:
        seen = set()
    result = []
    for dep in deps:
        dep = dep.strip()
        m = _SELF_REF.match(dep)
        if m:
            extras = [e.strip() for e in m.group(1).split(",")]
            for extra in extras:
                if extra in seen:
                    continue
                seen.add(extra)
                sub_deps = all_opts.get(extra, [])
                result.extend(expand_deps(sub_deps, all_opts, seen))
        else:
            result.append(dep)
    return result


def core_deps(data: dict) -> list[str]:
    return [flatten_dep(d) for d in data["project"]["dependencies"]]


def optional_deps(data: dict) -> dict[str, list[str]]:
    raw = data["project"]["optional-dependencies"]
    expanded = {}
    for group, deps in raw.items():
        expanded[group] = expand_deps([flatten_dep(d) for d in deps], raw)
    return expanded


def dedupe(seq: list[str]) -> list[str]:
    seen = set()
    out = []
    for item in seq:
        if item not in seen:
            seen.add(item)
            out.append(item)
    return out


def render_file(deps: list[str], extra: str | None = None) -> str:
    lines = [HEADER]
    if extra == "test":
        lines.append("-r requirements.txt\n")
    elif extra == "dev":
        lines.append("-r requirements-test.txt\n")
    lines.append("")
    for dep in dedupe(deps):
        lines.append(dep)
    if lines[-1] != "":
        lines.append("")
    return "\n".join(lines)


def write_if_changed(path: Path, content: str) -> bool:
    if path.exists() and path.read_text() == content:
        return False
    path.write_text(content)
    return True


def build_outputs(data: dict) -> dict[Path, str]:
    outputs = {}
    core = core_deps(data)
    opts = optional_deps(data)

    outputs[ROOT / "requirements.txt"] = render_file(core)

    outputs[ROOT / "requirements-test.txt"] = render_file(
        opts["test"], extra="test"
    )

    dev_extra = [d for d in opts["dev"] if d not in opts["test"]]
    outputs[ROOT / "requirements-dev.txt"] = render_file(
        dev_extra, extra="dev"
    )

    outputs[ROOT / "requirements-docs.txt"] = render_file(opts["docs"])

    return outputs


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check that generated files are up-to-date without writing",
    )
    args = parser.parse_args()

    data = parse_pyproject()
    outputs = build_outputs(data)

    changed: list[Path] = []
    for path, content in outputs.items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                changed.append(path)
        else:
            if write_if_changed(path, content):
                changed.append(path)

    if args.check:
        if changed:
            print("The following files are OUT OF DATE:")
            for p in changed:
                print(f"  {p.relative_to(ROOT)}")
                if p.exists():
                    actual = p.read_text()
                    expected = outputs[p]
                    diff = difflib.unified_diff(
                        actual.splitlines(keepends=True),
                        expected.splitlines(keepends=True),
                        fromfile=str(p.relative_to(ROOT)),
                        tofile=f"{p.relative_to(ROOT)} (expected)",
                    )
                    sys.stdout.writelines(diff)
            print("\nRun: python tools/generate_requirements.py")
            return 1
        print("All requirements files are up-to-date.")
        return 0

    if changed:
        print("Updated:")
        for p in changed:
            print(f"  {p.relative_to(ROOT)}")
    else:
        print("All requirements files are already up-to-date.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
